### ISSUE TITLE
Crash when using Firebase and devtodev

### ISSUE THREAD

**Issue by kroart** [devtodev-analytics/android-sdk#2]
Hi. I'm implementing devtodev sdk and my app crashing on startup. But crash occurs only on first app launch. On subsequent launches it doesn't crash. But if I uninstall app and reinstall it will again crash on first run.

If I remove either Firebase or DevToDev from project - everything works normally.

Here is crash log:
03-14 01:21:04.049 1718-1718/com.lazybonesgames.ornamentalsdkversionchecker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lazybonesgames.ornamentalsdkversionchecker, PID: 1718
    java.lang.RuntimeException: Unable to instantiate service com.devtodev.push.logic.DTDFcmMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.devtodev.push.logic.DTDFcmMessagingService" on path: DexPathList[[zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/base.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/lib/arm, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.devtodev.push.logic.DTDFcmMessagingService" on path: DexPathList[[zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/base.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.lazybonesgames.ornamentalsdkversionchecker-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap4(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.NoClassDefFoundError: com.devtodev.push.logic.DTDFcmMessagingService
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)

**Comment by Skazochnij** [comment]
Hello, please add latest version of firebase-messaging to your gradle file
`implementation 'com.google.firebase:firebase-messaging:X.Y.Z'`
